### ISSUE TITLE
no_std support?

### ISSUE THREAD

**Issue by Lokathor** [orlp/slotmap#26]
Can a flag be added to make this crate `no_std` and have it only depend on `alloc`?

**Comment by orlp** [comment]
This is implemented will be available in the upcoming version. By default the `std` feature is enabled, use `--no-default-features` to disable it. The only feature that goes missing is `SparseSecondaryMap`, as it relies on `HashMap` (maybe I can switch to `BTreeMap` for `no_std`? I'll check it out).

**Comment by orlp** [comment]
And 1.0 is now out which has `no_std` support.
