### ISSUE TITLE
Suport Entry API

### ISSUE THREAD

**Issue by mmstick** [orlp/slotmap#29]
I've been using slotmap to develop a disk management library for Linux with an ECS architecture with great success; at least with a `HopSlotMap<Entity, ()>` with many associated `SparseSecondaryMap<Entity, T>` storages.

Some secondary maps provide associations to zero or more other entities, such as a device with many children, or with many parents. Disks with partition tables, and LVM volume groups, would be an example of device entities that many contain many partitionable child device entities. LVM volume groups may themselves be a conglomeration of multiple parent devices.

This means that I have two secondary maps that are defined like so:

```rust
    // Devices that contain children will associate their children here.
    pub children: SparseSecondaryMap<Entity, Vec<Entity>>,
    // If the device has a parent, it will be associated here.
    pub parents: SparseSecondaryMap<Entity, Vec<Entity>>,
```

It would be ideal if I could fetch a key and insert a default value if it is vacant, or add value onto the map if it is not. Currently I have to `.get_mut()` and push on `Some(T)`, else `insert(vec![T])` on `None`.

```rust
match parents.get_mut(entity) {
    Some(associations) => associations.push(other_entity),
    None => drop(parents.insert(entity, vec![other_entity])),
}
```

**Comment by orlp** [comment]
I definitely agree that an entry API would be desirable.

However it would also be a very large amount of work. It is low on my priority list at the moment, sorry :(
