### ISSUE TITLE
Support `alter` method

### ISSUE THREAD

**Issue by singpolyma-shopify** [orlp/slotmap#30]
Just like the std hashmap -- very useful for update-or-delete style access

**Comment by orlp** [comment]
@singpolyma-shopify  I can't find an `alter` method for `std::collections::HashMap`, could you elaborate?

**Comment by singpolyma-shopify** [comment]
Oh wow, you're right. My bad.  Here's a map that does have this API though: https://docs.rs/chashmap/2.2.2/chashmap/struct.CHashMap.html#method.alter

**Comment by orlp** [comment]
I don't really feel this API is necessary. I would rather implement the standard `Entry` API (https://github.com/orlp/slotmap/issues/29). Using that you can efficiently implement this one if you so desire.

I think 0.4 or 0.5 of this library will have an `Entry` API, it's just a matter of me finding the time and motivation to add it.
