### ISSUE TITLE
How to get unique key types in builder pattern

### ISSUE THREAD

**Issue by NOP0** [orlp/slotmap#35]
Hi, I'm trying to wrap a slotmap in a generic struct. The intent is to be able to instantiate a slotmap for a given type with marker trait ImageEntity.  Im not sure how to use the ```new_key_type!``` macro in this context. Maybe my approach is wrong altogether? Thanks.

```
pub struct ProcessImageInputs<K: Key, T: ImageEntity> {
    image : SlotMap<K, T>,
}

impl <K, T>ProcessImageInputs<K, T> where
    T: ImageEntity,
    K : Key {

    pub fn new(size: usize, key_type : K ) -> Self {
        ProcessImageInputs{
            image: SlotMap::with_capacity_and_key(size),
        }
    }

**Comment by rebo** [comment]
How about something like this..

```rust

pub trait ImageEntity: Clone + Copy {
    type KeyType: Key + Copy + Eq + PartialEq;
}

// Shortcuts to the keytype and slotmap for a specific ImageEntity
pub type ImageEntityKey<E> = <E as ImageEntity>::KeyType;
pub type ImageEntitySlotMap<E> = SlotMap<<E as ImageEntity>::KeyType, E>;

// a Jpeg ImageEntity
#[derive(Clone, Copy)]
struct Jpeg {
    data: i32, //dummy jpeg image data
}

//if ImageEntity is implemented for Jpeg it will have an associated KeyType
impl ImageEntity for Jpeg {
    type KeyType = JpegKeyType;
}

pub type JpegKey = <Jpeg as ImageEntity>::KeyType;
new_key_type! {pub struct JpegKeyType;}

pub struct ProcessImageInputs<E: ImageEntity> {
    images: ImageEntitySlotMap<E>,
}

// generic struct that refers to structs that implement ImageEntity 
impl<E> ProcessImageInputs<E>
where
    E: ImageEntity,
{
    pub fn new(size: usize) -> Self {
        ProcessImageInputs {
            images: SlotMap::with_capacity_and_key(size),
        }
    }
}

fn run() {
    // new struct for processing JPEG files
    let mut process_jpeg: ProcessImageInputs<Jpeg> = ProcessImageInputs::new(10);
    // Will only allow JPEGs to be inserted because it only accepts ImageEntity's
    let jpeg_key = process_jpeg.images.insert(Jpeg { data: 1337 });

    // Jpegkey will have type ImageEntityKey<Jpeg>
}
```

**Comment by NOP0** [comment]
It really works! 👍 😄 

The solution with trait bounds on type aliases is new to me, and also the "casting" 
```<Jpeg as ImageEntity>::KeyType``` to get the actual associated type. Is this a new feature? Googling gave nothing.

Some of the types using this interface will be primitives like bool and f64. I guess I still need to wrap these in a newtype ie ```pub struct Bool(pub bool);``` ?

Thanks!

**Comment by rebo** [comment]
No Problem. 

As long as your types that you will store are Clone (which primitives will be) then you will be fine You just need to implement ImageEntity for them.

However ImageEntity trait will probably want to have things like key() and set_key() methods in order to retrieve a key from the object you are storing. A primitive type would not have these fields. In which case you probably need `struct BoolEntity {data:bool, key: BoolKey}` or something.

I.e. if you don't need the key stored with the object then the following should be perfectly fine:

```rust
// We need to a key for this image entity (once it is impl for bool)
new_key_type! {pub struct BoolKeyType;}

//if ImageEntity is implemented for bool it will have this associated KeyType
impl ImageEntity for Bool {
    type KeyType = BoolKeyType;
}

// shortcut to JpegKeyType.
pub type BoolKey = <Bool as ImageEntity>::KeyType;

fn run() {
    // new struct for processing Bool types
    let mut process_bool: ProcessImageInputs<Bool> = ProcessImageInputs::new(10);
    // Will only allow Bools to be inserted because it only accepts <Bool> ImageEntitys
    let bool_key = process_bool.images.insert(true);

    // Boolkey will have type ImageEntityKey<Bool> or even better BoolKey (a short cut type alias)
}

```

The 'casting' as a trait isnt a new feature as such but it does have some nuance to it. It just means that you can correctly select the associated type (in this case ::KeyType) from an object that implements a trait.

**Comment by NOP0** [comment]
Thanks!
