### ISSUE TITLE
Clone on slotmap::Iter

### ISSUE THREAD

**Issue by koalefant** [orlp/slotmap#37]
Hi, I am trying to use slotmap::keys().cycle().nth(pos).take(num) and get following error
```
src/main.rs|1394 col 14 error 277| the trait bound `slotmap::Iter<'_, MyKey, MyType>: std::clone::Clone` is not satisfied
||      |
|| 1394 |             .cycle()
||      |              ^^^^^ the trait `std::clone::Clone` is not implemented for `slotmap::Iter<'_, MyKey, MyType>`
```
are there any reasons why impl std::clone::Clone for Iter could not be added here?

**Comment by orlp** [comment]
Hey sorry, I'm very busy, I'll see if I have time tomorrow to check this out.

**Comment by orlp** [comment]
Sorry for the late response. This is fixed in the upcoming version.
