### ISSUE TITLE
Implement From<DenseSlotmap> for SecondaryMap

### ISSUE THREAD

**Issue by CGMossa** [orlp/slotmap#39]
Does this conversion make sense? If so, should it be included? 

My own context:
My example might be orthogonal to `slotmap`, but I have a struct that contains one `DenseSlotMap`,
and the rest are secondary maps that uses the keys from the first map. I choose one of them to be
the `DenseSlotMap` for no particular reason. Thus I am writing my functions that yield more `SecondaryMap`s as ones that take in `SecondaryMap`s.

**Comment by orlp** [comment]
Your use case is not entirely clear to me, could you explain some more?

**Comment by Uriopass** [comment]
As a workaround, you could have a DenseSlotmap that maps to `()` as a "key holding map" and then then have all your data stored in `SecondaryMap`s ?

**Comment by orlp** [comment]
I'm sorry, I still don't understand. Closing this.
