### ISSUE TITLE
NonZero Key tracking issue

### ISSUE THREAD

**Issue by artemshein** [orlp/slotmap#4]
It would be great to make the Key implement NonZero trait. The reason is that we could save space on Option<Key> and have all the Option ergonomics.

I'm not sure on the actual implementation we should take as NonZero trait is nightly only and also deprecated.

As a possible solution, we could use the Key(NonZeroU64) with a #[repr(transparent)] on it. Let me know if I could help with the implementation.

**Comment by orlp** [comment]
I don't believe that this is deprecated: https://doc.rust-lang.org/core/num/struct.NonZeroU32.html. The `version` field in `Key` is non-zero (because it is always odd).

**Comment by artemshein** [comment]
Nice to know that it's actually as simple as that.

**Comment by orlp** [comment]
With Rust 1.28 `std::num::NonZero*` has been stabilized so I can do this.

**Comment by orlp** [comment]
Solved by https://github.com/orlp/slotmap/commit/753a0207cbb084fc0265c41bc42a940c3b6a3bc7.
