### ISSUE TITLE
Non-copy values in slotmap on stable 1.49  🎉

### ISSUE THREAD

**Issue by Uriopass** [orlp/slotmap#46]
[With 1.49, ManuallyDrop in `union`s is coming on stable.](https://github.com/rust-lang/rust/pull/77547)

I see the code is already written using ManuallyDrop, which means that `slotmap` is already ready to be built on 1.49 and onwards! (I tested on beta)
However, it is currently under the `unstable` feature flag, which also enables the `TryReserve` API that, sadly, is not stable yet.  

What should be the course of action to enable users to use non-copy types on stable? 

I propose to remove the Slottable trait entirely and release a 0.5.0 version of the crate since this would break backward compatibility.

Another proposition would be to keep the `unstable` feature flag with the same semantics, and introduce a new flag to specifically enable non-copy types. 

I'd be happy to do the PR whichever way you prefer.

**Comment by orlp** [comment]
I'm waiting for the actual release before I do anything. Fear not, I will make `slotmap` require the least amount of features/dependencies as possible to function.

**Comment by orlp** [comment]
This is implemented and will be in the next version coming out soon.
