### ISSUE TITLE
`const SlotMap::new`?

### ISSUE THREAD

**Issue by ZetaNumbers** [orlp/slotmap#57]
I am trying to use `SlotMap`s in static context. To avoid lazy evaluation of these variables, i wonder could `SlotMap::new` ever be `const fn`? As i looked at the code and the only problematic thing i found was `vec` with only one element constructed. But I hope there is some way around that.

**Comment by orlp** [comment]
I'm sorry, this would limit other code too much, which assumes that a sentinel element exists.
