### ISSUE TITLE
Min const generics

### ISSUE THREAD

**Issue by Uriopass** [orlp/slotmap#58]
With min const generics in 1.51, `get_disjoint_mut` should now be usable in stable. It is gated behind the "unstable" feature, but sadly also behind the "nightly" feature.
```Rust
    #[cfg(all(nightly, any(doc, feature = "unstable")))]
```
It would be useful if the nightly part of the cfg could be removed.

**Comment by orlp** [comment]
Yeah, I'll get on that soon. I don't want to bump the minimum required Rust version so I'll detect it instead and remove the nightly tag if you have a recent enough Rust.

**Comment by Uriopass** [comment]
That's amazing! I didn't know you could do that :-)

**Comment by orlp** [comment]
Fixed in https://github.com/orlp/slotmap/commit/58605981724ce84080ccf150f1e43762aa3a5d66, available in release 1.0.3.
