### ISSUE TITLE
Non-mut iterators are not `Clone` if K and V are not `Clone`

### ISSUE THREAD

**Issue by ennis** [orlp/slotmap#62]
The iterators returned by `iter()` and `values()` cannot be cloned if the keys and values are not `Clone` themselves. 
I think this should not be necessary: for instance, [std::slice::Iter](https://doc.rust-lang.org/std/slice/struct.Iter.html) is `Clone` regardless of the element type.
To fix this, `Iter`, `Keys`, `Values` should implement Clone manually (`#[derive(Clone)]` adds extra `Clone` bounds on the type parameters: see https://github.com/rust-lang/rust/issues/26925)

**Comment by orlp** [comment]
Seems like a good idea, I will review your patch when I will make the next release of slotmap.
