### ISSUE TITLE
DenseSlotMap, HopSlotMap and SlotMap's ::with_capacity doesn't work with custom key.

### ISSUE THREAD

**Issue by EriKWDev** [orlp/slotmap#83]
The implementation of DenseSlotmap looks like this:
```rs
impl<V> DenseSlotMap<DefaultKey, V> {
    pub fn new() -> Self {
        Self::with_capacity_and_key(0)
    }

    pub fn with_capacity(capacity: usize) -> DenseSlotMap<DefaultKey, V> {
        Self::with_capacity_and_key(capacity)
    }
}
```

which forces the use of `DefaultKey`. Is this intentional or should it be `impl<K: Key, V> DenseSlotMap<K, V>`? Cannot use DenseSlotMap with a custom key created using `new_key_type!`.

**Comment by EriKWDev** [comment]
This appears to also be true for HopSlotMap:

```rust
 ​impl​<V> ​HopSlotMap​<DefaultKey, V> { /*...*/}
```

**Comment by orlp** [comment]
https://docs.rs/slotmap/latest/slotmap/dense/struct.DenseSlotMap.html#method.with_capacity_and_key
https://docs.rs/slotmap/latest/slotmap/struct.HopSlotMap.html#method.with_capacity_and_key

**Comment by EriKWDev** [comment]
I see, thanks!
