### ISSUE TITLE
How to differentiate between SlotMap instances of same type

### ISSUE THREAD

**Issue by georgewhewell** [orlp/slotmap#95]
Hey,

Sorry if this is mentioned somewhere/has obvious answer, couldn't see anywhere. In my program I create `SlotMap`s dynamically, and I'd like the keys to be unique per instance of the slotmap. 

```
use slotmap::*;

fn main() {
    let mut map_1 = SlotMap::new();
    let key_1 = map_1.insert("Hello");

    let mut map_2 = SlotMap::new();
    let key_2 = map_2.insert("Hello");

    println!("Has: {}", map_1.get(key_2).unwrap());
}
```

I'd like `map_1.get(key_2)` to return `None` (currently it returns `"Hello"`)

Is this possible?

Thanks

**Comment by orlp** [comment]
Yes, see [`new_key_type`](https://docs.rs/slotmap/latest/slotmap/macro.new_key_type.html).

**Comment by georgewhewell** [comment]
By _create SlotMaps dynamically_ I meant that the number of slotmaps is determined at runtime, so unless I am missing something, `new_key_type` macro  cannot help me?

**Comment by orlp** [comment]
@georgewhewell Sorry I read too quickly. In that case there is no support from `slotmap` itself to do this correctly. You'll have to come up with a scheme yourself, such as storing an additional identifier with the key that indicates which slotmap it is for.
