### ISSUE TITLE
Release a new slotmap minor version with try_insert_with_key support

### ISSUE THREAD

**Issue by turbocool3r** [orlp/slotmap#97]
A couple of years ago the [try_insert_with_key](https://github.com/orlp/slotmap/commit/223d022040bfa9d303a7bf69ee1b148fa8f35590) feature has been added. This feature would simplify a crate I'm currently writing. Is it possible to release a new version that includes that feature?

**Comment by orlp** [comment]
The good news: I'm actually doing work on 2.0 so it will be released hopefully this year or early 2024.

The bad news: I don't think I have the energy to also do minor releases for 1.x in the meantime.
